#[allow(unused_imports)]
use super::*;

pub(super) struct OtelCounters {
    pub(super) result_applied: Counter<u64>,
    pub(super) result_duplicate: Counter<u64>,
    pub(super) result_retried: Counter<u64>,
    pub(super) result_dead_lettered: Counter<u64>,
    pub(super) result_receive_errors: Counter<u64>,
    pub(super) handler_panics: Counter<u64>,
    pub(super) background_loop_failures: Counter<u64>,
    pub(super) ingress_applied: Counter<u64>,
    pub(super) ingress_retried: Counter<u64>,
    pub(super) ingress_dead_lettered: Counter<u64>,
    pub(super) triggers_fired: Counter<u64>,
    pub(super) vm_drive_ms: Histogram<f64>,
    pub(super) vm_continuations_driven: Counter<u64>,
    pub(super) vm_drive_duration_ms: Histogram<f64>,
    pub(super) vm_driver_failures: Counter<u64>,
    pub(super) loop_iterations: Counter<u64>,
    pub(super) loop_duration_ms: Histogram<f64>,
    pub(super) loop_last_success: Gauge<u64>,
    pub(super) cleanup: Counter<u64>,
    pub(super) queue_depth: Gauge<u64>,
    pub(super) queue_oldest_age: Gauge<u64>,
    pub(super) queue_claimed: Gauge<u64>,
    pub(super) queue_failures: Counter<u64>,
    pub(super) replicas: Gauge<u64>,
    pub(super) replica_heartbeat_age: Gauge<u64>,
    pub(super) replica_transitions: Counter<u64>,
    pub(super) adapter_poll_attempts: Counter<u64>,
    pub(super) adapter_poll_duration_ms: Histogram<f64>,
    pub(super) adapter_delivery_outcomes: Counter<u64>,
}
