import "./bootstrap";
import "@fontsource/inter/latin-400.css";
import "@fontsource/inter/latin-500.css";
import "@fontsource/inter/latin-600.css";
import "@fontsource/inter/latin-700.css";
import "@fontsource/jetbrains-mono/latin-400.css";
import "@fontsource/jetbrains-mono/latin-500.css";
import "@fontsource/jetbrains-mono/latin-600.css";
import "@fontsource/jetbrains-mono/latin-700.css";
import { createApp } from "vue";
import App from "./App.vue";
import DataTable from "./ui/components/shared/DataTable.vue";
import "@vue-flow/core/dist/style.css";
import "./styles/base.css";
import "./styles/tailwind.css";
import "./styles/layout.css";
import "./styles/workflow.css";
import { createPinia } from "pinia";
createApp(App).use(createPinia()).component("DataTable", DataTable).mount("#app");
