apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: runinator

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: runinator

resources:
  - namespace.yaml
  - common-config.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - ws.yaml
  - archiver.yaml
  - waker.yaml
  - worker.yaml
  - pack-import.yaml
  - command-center.yaml
  - autoscaling.yaml
  - pdb.yaml

images:
  - name: runinator-ws
    newTag: dev
  - name: runinator-waker
    newTag: dev
  - name: runinator-worker
    newTag: dev
  - name: runinator-archiver
    newTag: dev
  - name: runinator-ctl
    newTag: dev
  - name: runinator-bootstrap
    newTag: dev
  - name: runinator-command-center
    newTag: dev
