[package]
name = "runinator-provider-std"
version.workspace = true
edition = "2024"

[dependencies]
serde_json = "1.0"
reqwest = { version = "0.13.3", default-features = false, features = ["json", "rustls", "blocking"] }
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["clock"] }

runinator-plugin = { path = "../runinator-plugin" }
runinator-models = { path = "../runinator-models" }
runinator-compute = { path = "../runinator-compute" }
runinator-sandbox = { path = "../runinator-sandbox" }
