apiVersion: v1
kind: Namespace
metadata:
  name: runinator
---
apiVersion: v1
kind: Service
metadata:
  name: runinator-gossip
  namespace: runinator
spec:
  selector:
    app: runinator-scheduler
  ports:
    - name: gossip
      port: 5511
      protocol: UDP
      targetPort: 5511
---
apiVersion: v1
kind: Service
metadata:
  name: runinator-ws
  namespace: runinator
spec:
  selector:
    app: runinator-ws
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: runinator-broker
  namespace: runinator
spec:
  selector:
    app: runinator-broker
  ports:
    - name: http
      port: 7070
      targetPort: 7070
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runinator-scheduler
  namespace: runinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runinator-scheduler
  template:
    metadata:
      labels:
        app: runinator-scheduler
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: scheduler
          image: your-registry/runinator-scheduler:latest
          imagePullPolicy: IfNotPresent
          command:
            - runinator-scheduler
          args:
            - '--scheduler-frequency-seconds'
            - '1'
            - '--gossip-bind'
            - '0.0.0.0'
            - '--gossip-port'
            - '5511'
            - '--gossip-targets'
            - 'runinator-gossip.runinator.svc.cluster.local:5511'
            - '--api-timeout-seconds'
            - '30'
            - '--broker-backend'
            - 'http'
            - '--broker-endpoint'
            - 'http://runinator-broker.runinator.svc.cluster.local:7070/'
            - '--broker-poll-timeout-seconds'
            - '5'
          env:
            - name: RUST_LOG
              value: info
          volumeMounts:
            - name: scheduler-data
              mountPath: /var/runinator
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: scheduler-data
          hostPath:
            path: __HOST_VOLUME_ROOT__/scheduler
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runinator-worker
  namespace: runinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runinator-worker
  template:
    metadata:
      labels:
        app: runinator-worker
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: worker
          image: your-registry/runinator-worker:latest
          imagePullPolicy: IfNotPresent
          command:
            - runinator-worker
          args:
            - '--dll-path'
            - '/opt/runinator/plugins'
            - '--broker-backend'
            - 'http'
            - '--broker-endpoint'
            - 'http://runinator-broker.runinator.svc.cluster.local:7070/'
            - '--broker-poll-timeout-seconds'
            - '5'
            - '--api-base-url'
            - 'http://runinator-ws.runinator.svc.cluster.local:8080/'
          env:
            - name: RUST_LOG
              value: info
          volumeMounts:
            - name: worker-data
              mountPath: /var/runinator
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: worker-data
          hostPath:
            path: __HOST_VOLUME_ROOT__/worker
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runinator-importer
  namespace: runinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runinator-importer
  template:
    metadata:
      labels:
        app: runinator-importer
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: importer
          image: your-registry/runinator-importer:latest
          imagePullPolicy: IfNotPresent
          command:
            - runinator-importer
          args:
            - '--tasks-file'
            - '/opt/runinator/tasks/tasks.json'
            - '--poll-interval-seconds'
            - '30'
            - '--gossip-bind'
            - '0.0.0.0'
            - '--gossip-port'
            - '5512'
            - '--gossip-targets'
            - 'runinator-gossip.runinator.svc.cluster.local:5511'
          env:
            - name: RUST_LOG
              value: info
          volumeMounts:
            - name: importer-data
              mountPath: /var/runinator
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: importer-data
          hostPath:
            path: __HOST_VOLUME_ROOT__/importer
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runinator-ws
  namespace: runinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runinator-ws
  template:
    metadata:
      labels:
        app: runinator-ws
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: web
          image: your-registry/runinator-ws:latest
          imagePullPolicy: IfNotPresent
          command:
            - runinator-ws
          args:
            - '--database'
            - 'postgres'
            - '--database-url'
            - 'postgresql://runinator:runinator@runinator-postgres.runinator.svc.cluster.local:5432/runinator'
            - '--port'
            - '8080'
            - '--gossip-bind'
            - '0.0.0.0'
            - '--gossip-port'
            - '5510'
            - '--gossip-targets'
            - 'runinator-gossip.runinator.svc.cluster.local:5511'
            - '--announce-address=$(POD_IP)'
            - '--announce-base-path'
            - '/'
          env:
            - name: RUST_LOG
              value: info
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: web-data
              mountPath: /var/runinator
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: web-data
          hostPath:
            path: __HOST_VOLUME_ROOT__/web
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runinator-broker
  namespace: runinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runinator-broker
  template:
    metadata:
      labels:
        app: runinator-broker
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: broker
          image: your-registry/runinator-broker:latest
          imagePullPolicy: IfNotPresent
          command:
            - runinator-broker
          env:
            - name: RUST_LOG
              value: info
            - name: RUNINATOR_BROKER_ADDR
              value: 0.0.0.0:7070
            - name: RUNINATOR_BROKER_BACKEND
              value: __BROKER_BACKEND__
          ports:
            - containerPort: 7070
              name: http
              protocol: TCP
          volumeMounts:
            - name: broker-data
              mountPath: /var/runinator
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: broker-data
          hostPath:
            path: __HOST_VOLUME_ROOT__/broker
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runinator-postgres
  namespace: runinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runinator-postgres
  template:
    metadata:
      labels:
        app: runinator-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: runinator
            - name: POSTGRES_USER
              value: runinator
            - name: POSTGRES_PASSWORD
              value: runinator
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: postgres-data
          hostPath:
            path: __HOST_VOLUME_ROOT__/postgres
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: runinator-postgres
  namespace: runinator
spec:
  selector:
    app: runinator-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
---
# BROKER_INFRA_PLACEHOLDER
