apiVersion: v1
kind: Namespace
metadata:
  name: runinator
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runinator-shared-data
  namespace: runinator
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: runinator-gossip
  namespace: runinator
spec:
  selector:
    app: runinator-scheduler
  ports:
    - name: gossip
      port: 5000
      protocol: UDP
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runinator-scheduler
  namespace: runinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runinator-scheduler
  template:
    metadata:
      labels:
        app: runinator-scheduler
    spec:
      containers:
        - name: scheduler
          image: your-registry/runinator-scheduler:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - >
              runinator-scheduler
              --gossip-bind 0.0.0.0
              --gossip-port 5000
              --gossip-targets runinator-gossip.runinator.svc.cluster.local
              --worker-timeout-seconds 60
              --worker-command-retry 3
              --api-timeout-seconds 30
          env:
            - name: RUST_LOG
              value: info
          ports:
            - containerPort: 5000
              name: gossip
              protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runinator-worker
  namespace: runinator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: runinator-worker
  template:
    metadata:
      labels:
        app: runinator-worker
    spec:
      containers:
        - name: worker
          image: your-registry/runinator-worker:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - >
              runinator-worker
              --dll-path /opt/runinator/plugins
              --gossip-bind 0.0.0.0
              --gossip-port 5000
              --gossip-targets runinator-gossip.runinator.svc.cluster.local
              --announce-address "$POD_IP"
              --command-bind 0.0.0.0
              --command-port 7100
          env:
            - name: RUST_LOG
              value: info
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 7100
              name: worker-cmd
              protocol: TCP
          volumeMounts:
            - name: worker-host-volume
              mountPath: /data
      volumes:
        - name: worker-host-volume
          hostPath:
            path: /var/runinator
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runinator-importer
  namespace: runinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runinator-importer
  template:
    metadata:
      labels:
        app: runinator-importer
    spec:
      containers:
        - name: importer
          image: your-registry/runinator-importer:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - >
              runinator-importer
              --gossip-bind 0.0.0.0
              --gossip-port 5000
              --gossip-targets runinator-gossip.runinator.svc.cluster.local
              --tasks-file /opt/runinator/tasks/tasks.json
              --poll-interval-seconds 30
          env:
            - name: RUST_LOG
              value: info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runinator-ws
  namespace: runinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runinator-ws
  template:
    metadata:
      labels:
        app: runinator-ws
    spec:
      containers:
        - name: web
          image: your-registry/runinator-ws:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - >
              runinator-ws
              --database sqlite
              --sqlite-path /data/tasks.db
              --port 8080
              --gossip-bind 0.0.0.0
              --gossip-port 5000
              --gossip-targets runinator-gossip.runinator.svc.cluster.local
              --announce-address "$POD_IP"
          env:
            - name: RUST_LOG
              value: info
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: scheduler-data
              mountPath: /data
      volumes:
        - name: scheduler-data
          persistentVolumeClaim:
            claimName: runinator-shared-data
---
apiVersion: v1
kind: Service
metadata:
  name: runinator-ws
  namespace: runinator
spec:
  type: NodePort
  selector:
    app: runinator-ws
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
