//! the hidden workflow that stands behind a direct function invocation.
//!
//! `POST /functions/{package}/{export}/invocations` does not run code by itself — it starts a
//! *workflow run*. that is the point: retry, timeout, cancellation, logs, artifacts, tracing, and
//! the debugger are all properties of a run, and an http path that executed a container directly
//! would need its own copy of every one of them and would drift from the workflow path immediately.
//!
//! so publishing generates one single-node workflow per export. it is marked
//! `metadata.managed_by = "functions"` so it stays out of the workflow list, and it is generated by
//! **compiling WDL** rather than by assembling graph json: the compiler is what guarantees the graph
//! is well-formed, and it is the same path that produced every other workflow in the system.

use runinator_database::interfaces::DatabaseImpl;
use runinator_models::errors::SendableError;
use runinator_models::functions::{FunctionCatalogEntry, FunctionExport};
use runinator_models::providers::ParameterMetadata;
use runinator_models::types::RuninatorType;
use runinator_models::value::Value;
use runinator_models::workflows::WorkflowDefinition;
use uuid::Uuid;

use crate::errors::FUNCTION_NOT_FOUND;

/// the `metadata.managed_by` value an adapter workflow carries.
///
/// the same key pack-managed triggers and notification policies use, so one convention covers
/// "this row is generated; do not hand-edit it".
pub const MANAGED_BY: &str = "functions";

/// the reserved namespace adapter workflows live in, keeping their names from colliding with an
/// author's.
pub const ADAPTER_NAMESPACE: &str = "functions";

/// the workflow name for one export's adapter.
pub fn adapter_workflow_name(entry: &FunctionCatalogEntry) -> String {
    format!("{}.{}", entry.provider_name(), entry.export_name)
}

/// generate (or regenerate) the adapter workflows for a package's current exports.
///
/// keyed on the export id, so republishing a package mints new adapters for the new version's
/// exports and leaves the old ones pointing at the old code — which is what keeps an in-flight
/// invocation of the previous version running exactly what it started.
pub async fn sync_adapter_workflows<T: DatabaseImpl>(
    db: &T,
    package_id: Uuid,
) -> Result<Vec<WorkflowDefinition>, SendableError> {
    let entries: Vec<FunctionCatalogEntry> = db
        .fetch_function_catalog()
        .await?
        .into_iter()
        .filter(|entry| entry.package_id == package_id)
        .collect();
    let Some(package) = db.fetch_function_package_by_id(package_id).await? else {
        return Ok(Vec::new());
    };

    // only the newest version of each export gets an adapter: the http path is the "call the current
    // release" surface, and a caller that wants an exact version names it in a workflow instead.
    let mut newest: std::collections::BTreeMap<String, FunctionCatalogEntry> =
        std::collections::BTreeMap::new();
    for entry in entries {
        newest
            .entry(entry.export_name.clone())
            .and_modify(|current| {
                if entry.version > current.version {
                    *current = entry.clone();
                }
            })
            .or_insert(entry);
    }

    let mut generated = Vec::with_capacity(newest.len());
    for entry in newest.values() {
        let Some(export) = db.fetch_function_export(entry.export_id).await? else {
            continue;
        };
        let mut definition = build_adapter_workflow(entry, &export)?;
        definition.org_id = package.org_id;
        // reuse the stored id so regenerating updates in place rather than orphaning a workflow the
        // adapter table still points at.
        if let Some(existing) = db.fetch_workflow_by_name(definition.name.clone()).await? {
            definition.id = existing.id;
        }
        let saved = super::definitions::upsert_workflow(
            db,
            &definition,
            &runinator_models::revisions::RevisionAuthor {
                source: runinator_models::revisions::RevisionSource::Api,
                actor_id: None,
                actor_kind: MANAGED_BY.to_string(),
                note: Some(format!(
                    "generated for {} version {}",
                    entry.export_name, entry.version
                )),
            },
        )
        .await?;
        if let Some(workflow_id) = saved.id {
            db.upsert_function_adapter_workflow(entry.export_id, workflow_id)
                .await?;
        }
        generated.push(saved);
    }
    Ok(generated)
}

/// the adapter workflow for one export, compiled from generated WDL.
pub fn build_adapter_workflow(
    entry: &FunctionCatalogEntry,
    export: &FunctionExport,
) -> Result<WorkflowDefinition, SendableError> {
    let source = adapter_source(entry, export);
    let options = runinator_wdl::CompileOptions {
        enabled: true,
        functions: vec![entry.clone()],
        ..runinator_wdl::CompileOptions::default()
    };
    let mut definition = runinator_wdl::compile_str(&source, &options).map_err(|err| {
        FUNCTION_NOT_FOUND.error(format!(
            "could not generate an adapter workflow for '{}': {err}",
            entry.export_name
        ))
    })?;
    // stamped after compilation because the marker is ours, not the source's: nothing an author
    // could write should be able to claim a workflow is function-managed.
    stamp_managed(&mut definition, entry);
    Ok(definition)
}

/// the WDL an adapter workflow is compiled from.
///
/// one node, one call, and the export's declared inputs as workflow params — so the http request
/// body is validated against the same schema a workflow call is type-checked against.
fn adapter_source(entry: &FunctionCatalogEntry, export: &FunctionExport) -> String {
    let mut source = format!(
        "workflow \"{}\" v1 {{\n",
        adapter_workflow_name(entry).replace('"', "")
    );
    if !export.input.is_empty() {
        source.push_str("    params {\n");
        for parameter in &export.input {
            source.push_str(&format!(
                "        {}: {}\n",
                parameter.name,
                wdl_type(parameter)
            ));
        }
        source.push_str("    }\n");
    }
    let args = export
        .input
        .iter()
        .map(|parameter| format!("{}: params.{}", parameter.name, parameter.name))
        .collect::<Vec<_>>()
        .join(", ");
    source.push_str(&format!(
        "    node invoke <- {}.{}({args})\n",
        entry.provider_name(),
        entry.export_name
    ));
    // no `output` block: that is wdl's *artifact* declaration, not the run result. the single
    // action node's output is already the run's, which is what the invocation endpoint reads back.
    source.push_str("}\n");
    source
}

// the surface type name for a declared parameter. anything structural renders as `any`: the
// export's real schema still types the call, and an adapter that failed to compile because a
// nested struct could not be spelled would take the whole publish down with it.
fn wdl_type(parameter: &ParameterMetadata) -> &'static str {
    match parameter.ty {
        RuninatorType::String => "string",
        RuninatorType::Integer => "integer",
        RuninatorType::Number => "number",
        RuninatorType::Boolean => "boolean",
        _ => "any",
    }
}

// mark the workflow as generated, and record which export it stands for so the invocation path can
// find its way back without a second table lookup.
fn stamp_managed(definition: &mut WorkflowDefinition, entry: &FunctionCatalogEntry) {
    let mut metadata = match &definition.definition.metadata {
        Value::Object(object) => object.clone(),
        _ => Default::default(),
    };
    metadata.insert("managed_by".into(), Value::String(MANAGED_BY.into()));
    metadata.insert(
        "namespace".into(),
        Value::String(ADAPTER_NAMESPACE.to_string()),
    );
    metadata.insert(
        "function".into(),
        runinator_models::json!({
            "package": entry.package_name.clone(),
            "namespace": entry.namespace.clone(),
            "export": entry.export_name.clone(),
            "version": entry.version,
            "export_id": entry.export_id,
        }),
    );
    definition.definition.metadata = Value::Object(metadata);
}

/// the adapter workflow generated for one export, if it has one.
///
/// through the repository rather than straight off the store because it is the invocation path's
/// join from "an export" to "a run to start" — orchestration, not crud.
pub async fn fetch_adapter_workflow<T: DatabaseImpl>(
    db: &T,
    export_id: Uuid,
) -> Result<Option<runinator_models::functions::FunctionAdapterWorkflow>, SendableError> {
    db.fetch_function_adapter_workflow(export_id).await
}

/// true when a workflow is a generated function adapter rather than an authored workflow.
pub fn is_adapter_workflow(definition: &WorkflowDefinition) -> bool {
    definition
        .definition
        .metadata
        .get("managed_by")
        .and_then(Value::as_str)
        == Some(MANAGED_BY)
}

#[cfg(test)]
#[path = "function_adapters_tests.rs"]
mod tests;
