-- A per-row UUID generated by MySQL for the one-time legacy backfill. New writes mint UUIDv7
-- values in the application and preserve them on the path-key conflict update.
ALTER TABLE settings ADD COLUMN id BINARY(16) NULL;
UPDATE settings SET id = UNHEX(REPLACE(UUID(), '-', '')) WHERE id IS NULL;
CREATE UNIQUE INDEX idx_settings_id ON settings(id);
