const DEFAULT_INPUT_MAX_LENGTH = 256;
const DEFAULT_TEXTAREA_MAX_LENGTH = 16 * 1024;
const DEFAULT_URL_MAX_LENGTH = 2 * 1024;

export type FormControl = HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement;

function isTextualInput(control: HTMLInputElement): boolean {
  return ["", "email", "password", "search", "tel", "text", "url"].includes(control.type);
}

function isEditorControl(control: FormControl): boolean {
  return Boolean(control.closest(".cm-editor, .terminal-surface"));
}

function hasUnsupportedControlCharacter(value: string): boolean {
  for (const character of value) {
    const codePoint = character.codePointAt(0) ?? 0;

    if (
      (codePoint <= 31 && ![9, 10, 13].includes(codePoint)) ||
      (codePoint >= 127 && codePoint <= 159)
    ) {
      return true;
    }
  }

  return false;
}

function controlsWithin(root: ParentNode): FormControl[] {
  const controls = [...root.querySelectorAll<FormControl>("input, select, textarea")];

  if (
    root instanceof HTMLInputElement ||
    root instanceof HTMLSelectElement ||
    root instanceof HTMLTextAreaElement
  ) {
    controls.unshift(root);
  }

  return controls;
}

/** Apply safe default bounds even to controls generated by dynamic metadata editors. */
export function applyDefaultConstraints(root: ParentNode): void {
  for (const control of controlsWithin(root)) {
    if (control.dataset.validation === "unbounded" || isEditorControl(control)) {
      continue;
    }

    if (control instanceof HTMLTextAreaElement && control.maxLength < 0) {
      control.maxLength = DEFAULT_TEXTAREA_MAX_LENGTH;
    }

    if (control instanceof HTMLInputElement && isTextualInput(control) && control.maxLength < 0) {
      control.maxLength =
        control.type === "password"
          ? DEFAULT_TEXTAREA_MAX_LENGTH
          : control.type === "url"
            ? DEFAULT_URL_MAX_LENGTH
            : DEFAULT_INPUT_MAX_LENGTH;
    }
  }
}

/** Add semantic checks the browser's native constraint API does not cover. */
export function validateFormControl(control: FormControl): boolean {
  control.setCustomValidity("");

  if (control.disabled || !control.willValidate || control.dataset.validation === "unbounded") {
    return true;
  }

  if (
    control.required &&
    !(control instanceof HTMLSelectElement) &&
    control.value.trim().length === 0
  ) {
    control.setCustomValidity("Enter a value that is not only whitespace.");
    return false;
  }

  if (control instanceof HTMLInputElement && control.type === "number" && control.value) {
    const value = Number(control.value);

    if (!Number.isFinite(value)) {
      control.setCustomValidity("Enter a finite number.");
      return false;
    }

    if (control.step === "1" && !Number.isInteger(value)) {
      control.setCustomValidity("Enter a whole number.");
      return false;
    }
  }

  const validators = new Set(
    (control.dataset.validation ?? "")
      .split(/\s+/)
      .map((value) => value.trim())
      .filter(Boolean),
  );
  const value = control.value.trim();

  if (
    !(control instanceof HTMLSelectElement) &&
    control.maxLength >= 0 &&
    control.value.length > control.maxLength
  ) {
    control.setCustomValidity(`Use at most ${String(control.maxLength)} characters.`);
    return false;
  }

  if (
    (control instanceof HTMLTextAreaElement ||
      (control instanceof HTMLInputElement && isTextualInput(control))) &&
    hasUnsupportedControlCharacter(control.value)
  ) {
    control.setCustomValidity("Remove control characters from this value.");
    return false;
  }

  if (value && validators.has("json")) {
    try {
      JSON.parse(value);
    } catch {
      control.setCustomValidity("Enter valid JSON.");
      return false;
    }
  }

  if (value && control instanceof HTMLInputElement && control.type === "url") {
    try {
      const url = new URL(value);

      if (!(["http:", "https:"] as string[]).includes(url.protocol) || !url.hostname) {
        throw new Error("unsupported URL");
      }
    } catch {
      control.setCustomValidity("Enter an absolute http:// or https:// URL.");
      return false;
    }
  }

  if (value && validators.has("identifier") && !/^[A-Za-z0-9._/:-]+$/.test(value)) {
    control.setCustomValidity("Use only letters, numbers, '.', '_', '/', ':', and '-'.");
    return false;
  }

  if (
    value &&
    validators.has("uuid") &&
    !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
  ) {
    control.setCustomValidity("Enter a valid UUID.");
    return false;
  }

  const afterSelector = control.dataset.after;

  if (value && afterSelector) {
    const previous = document.querySelector<HTMLInputElement>(afterSelector);

    if (previous?.value && new Date(value).getTime() <= new Date(previous.value).getTime()) {
      control.setCustomValidity(
        `Choose a value later than ${previous.getAttribute("aria-label") ?? "the start"}.`,
      );
      return false;
    }
  }

  return control.validity.valid;
}

/** Validate a whole form or editor surface, including controls the user has not touched yet. */
export function validateFormControls(root: ParentNode): FormControl | null {
  applyDefaultConstraints(root);
  let firstInvalid: FormControl | null = null;

  for (const control of controlsWithin(root)) {
    if (!validateFormControl(control) && !firstInvalid) {
      firstInvalid = control;
    }
  }

  return firstInvalid;
}
