const DEFAULT_INPUT_MAX_LENGTH = 256;
const DEFAULT_TEXTAREA_MAX_LENGTH = 16 * 1024;

type FormControl = HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement;

function isTextualInput(control: HTMLInputElement): boolean {
  return ["", "email", "password", "search", "tel", "text", "url"].includes(control.type);
}

function isEditorControl(control: FormControl): boolean {
  return Boolean(control.closest(".cm-editor, .terminal-surface"));
}

/** Apply safe default bounds even to controls generated by dynamic metadata editors. */
export function applyDefaultConstraints(root: ParentNode): void {
  for (const control of root.querySelectorAll<FormControl>("input, select, textarea")) {
    if (control.dataset.validation === "unbounded" || isEditorControl(control)) {
      continue;
    }

    if (control instanceof HTMLTextAreaElement && control.maxLength < 0) {
      control.maxLength = DEFAULT_TEXTAREA_MAX_LENGTH;
    }

    if (control instanceof HTMLInputElement && isTextualInput(control) && control.maxLength < 0) {
      control.maxLength = DEFAULT_INPUT_MAX_LENGTH;
    }
  }
}

/** Add semantic checks the browser's native constraint API does not cover. */
export function validateFormControl(control: FormControl): boolean {
  control.setCustomValidity("");

  if (control.disabled || control.dataset.validation === "unbounded") {
    return true;
  }

  if (
    control.required &&
    !(control instanceof HTMLSelectElement) &&
    control.value.trim().length === 0
  ) {
    control.setCustomValidity("Enter a value that is not only whitespace.");
    return false;
  }

  if (control instanceof HTMLInputElement && control.type === "number" && control.value) {
    const value = Number(control.value);

    if (!Number.isFinite(value)) {
      control.setCustomValidity("Enter a finite number.");
      return false;
    }

    if (control.step === "1" && !Number.isInteger(value)) {
      control.setCustomValidity("Enter a whole number.");
      return false;
    }
  }

  const validators = new Set(
    (control.dataset.validation ?? "")
      .split(/\s+/)
      .map((value) => value.trim())
      .filter(Boolean),
  );
  const value = control.value.trim();

  if (value && validators.has("json")) {
    try {
      JSON.parse(value);
    } catch {
      control.setCustomValidity("Enter valid JSON.");
      return false;
    }
  }

  if (value && validators.has("identifier") && !/^[A-Za-z0-9._/:-]+$/.test(value)) {
    control.setCustomValidity("Use only letters, numbers, '.', '_', '/', ':', and '-'.");
    return false;
  }

  if (
    value &&
    validators.has("uuid") &&
    !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
  ) {
    control.setCustomValidity("Enter a valid UUID.");
    return false;
  }

  const afterSelector = control.dataset.after;

  if (value && afterSelector) {
    const previous = document.querySelector<HTMLInputElement>(afterSelector);

    if (previous?.value && new Date(value).getTime() <= new Date(previous.value).getTime()) {
      control.setCustomValidity(
        `Choose a value later than ${previous.getAttribute("aria-label") ?? "the start"}.`,
      );
      return false;
    }
  }

  return control.validity.valid;
}
