[package]
name = "runinator-rexrap-codegen"
version.workspace = true
edition = "2024"

[dependencies]
serde_json = "1"
runinator-models = { path = "../runinator-models" }
runinator-compute = { path = "../runinator-compute" }
runinator-rexrap-syntax = { path = "../runinator-rexrap-syntax" }
runinator-rexrap-sema = { path = "../runinator-rexrap-sema" }
