[package]
name = "runinator-database"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
log = "0.4"
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-native-tls", "macros"] }

runinator-models = { path = "../runinator-models" }