// vocabulary shared by rexrap tokenization and static completion.

// keyword groups mirror runinator-rexrap/src/rexrap.pest, split by role so each gets its own color.
// structural declarations that open blocks or bind names.
export const DECL_KW = new Set([
  "workflow",
  "params",
  "input",
  "node",
  "let",
  "type",
  "alias",
  "trigger",
  "correlate",
  "start",
  "set",
  "secret",
  "config",
  "fn",
  "namespace",
  "import",
]);
// control-flow statements and block headers.
export const CONTROL_KW = new Set([
  "if",
  "else",
  "for",
  "while",
  "until",
  "match",
  "when",
  "toggle",
  "split",
  "on",
  "off",
  "parallel",
  "race",
  "try",
  "catch",
  "finally",
  "map",
  "branch",
  "join",
  "wait",
  "emit",
  "output",
  "yield",
  "approve",
  "fail",
  "subflow",
  "do",
  "return",
  "goto",
  "edges",
  "gate",
  "signal",
  "watch",
  "interrupt",
  "resume",
  "compensate",
  "assert",
  "transform",
  "audit",
  "checkpoint",
  "mutex",
  "throttle",
  "cooldown",
  "await",
  "debounce",
  "collect",
  "barrier",
  "circuit_breaker",
  "event_source",
]);
// clause/option words that modify a statement.
export const MODIFIER_KW = new Set([
  "with",
  "as",
  "initial",
  "limit",
  "concurrency",
  "detached",
  "reuse",
  "disabled",
  "blackout",
  "to",
  "cron",
  "on_success",
  "on_failure",
  "on_complete",
  "winner",
  "name",
  "meta",
  "returns",
  "every",
  "timeout",
  "hold",
  "release",
  "key",
  "priority",
  "max_depth",
  "rate",
  "per",
  "delay",
  "count",
  "threshold",
  "window",
  "cooldown",
  "mode",
  "action",
  "actor",
  "target",
  "reason",
  "filter",
]);
// word-form comparison/membership operators.
export const OP_KW = new Set(["exists", "contains", "in", "starts_with", "ends_with"]);
// outcome labels, only highlighted as such when they precede a `->` transition.
export const OUTCOMES = new Set(["ok", "next", "fail", "timeout", "reject"]);
// constant-like policy/target atoms.
export const ATOMS = new Set([
  "all",
  "any",
  "first_success",
  "done",
  "none",
  "manual",
  "condition",
  // interrupt sources. `external` and `timeout` are already spelled here / among the modifiers.
  "external",
  "wake",
  "retry",
  "failure",
  "resolved",
  "child",
  "orphan_signal",
]);
// coercion and compile-time intrinsics, highlighted as functions only when called.
export const BUILTINS = new Set(["string", "json", "file", "dir", "inline"]);
// reference roots that are never keywords.
export const PURE_REFS = new Set(["run", "loop", "state", "item"]);
// roots that double as keywords; treated as a reference only before a `.`. `std` is the builtin
// standard-library namespace root (`std.strings.upper(...)`).
export const ROOT_KEYWORDS = new Set(["params", "config", "secret", "workflow", "std"]);
// primitive type names. surfaced for completion, and colored inside type-position contexts
// (after `type`/`:` in a type field, `node x:`/`let x:` annotations) where they are unambiguous.
export const TYPES = [
  "any",
  "boolean",
  "bool",
  "duration",
  "float",
  "int",
  "integer",
  "json",
  "map",
  "null",
  "number",
  "string",
];

export const STD_MODULES = [
  "math",
  "strings",
  "collections",
  "objects",
  "encoding",
  "logic",
  "dates",
  "regex",
  "exec",
] as const;

export const STD_INTRINSICS: { label: string; module: (typeof STD_MODULES)[number] }[] = [
  ...[
    "add",
    "sub",
    "mul",
    "div",
    "mod",
    "floor",
    "ceil",
    "round",
    "min",
    "max",
    "parse_int",
    "parse_float",
  ].map((label) => ({ label, module: "math" as const })),
  ...[
    "lower",
    "upper",
    "trim",
    "split",
    "join",
    "replace",
    "substring",
    "starts_with",
    "ends_with",
  ].map((label) => ({ label, module: "strings" as const })),
  ...[
    "len",
    "keys",
    "values",
    "contains",
    "at",
    "has",
    "sum",
    "sort",
    "reverse",
    "unique",
    "flatten",
    "slice",
    "first",
    "last",
    "append",
    "range",
    "map",
    "filter",
    "find",
    "any",
    "all",
    "reduce",
    "sort_by",
    "flat_map",
  ].map((label) => ({ label, module: "collections" as const })),
  ...["merge", "pick", "omit", "entries", "from_entries"].map((label) => ({
    label,
    module: "objects" as const,
  })),
  ...["parse_json", "base64_encode", "base64_decode"].map((label) => ({
    label,
    module: "encoding" as const,
  })),
  ...["eq", "ne", "gt", "lt", "gte", "lte", "not", "and", "or", "default"].map((label) => ({
    label,
    module: "logic" as const,
  })),
  ...["format_date", "parse_date", "add_duration", "date_diff"].map((label) => ({
    label,
    module: "dates" as const,
  })),
  ...["regex_match", "regex_replace", "regex_extract"].map((label) => ({
    label,
    module: "regex" as const,
  })),
  ...["http_get", "http_post", "now", "uuid", "env"].map((label) => ({
    label,
    module: "exec" as const,
  })),
];

// completion vocabulary spans every group so suggestions stay broad.
export const KEYWORDS = new Set([
  ...DECL_KW,
  ...CONTROL_KW,
  ...MODIFIER_KW,
  ...OP_KW,
  ...OUTCOMES,
  ...ATOMS,
  ...BUILTINS,
  ...PURE_REFS,
  ...ROOT_KEYWORDS,
  ...TYPES,
  "true",
  "false",
  "null",
]);
