[package]
name = "runinator-provider-local-files"
version.workspace = true
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
mime_guess = "2"

runinator-plugin = { path = "../runinator-plugin" }
runinator-models = { path = "../runinator-models" }
runinator-provider-support = { path = "../runinator-provider-support" }
