[package]
name = "runinator-wdl-codegen"
version.workspace = true
edition = "2024"

[dependencies]
serde_json = "1"
runinator-models = { path = "../runinator-models" }
runinator-compute = { path = "../runinator-compute" }
runinator-wdl-syntax = { path = "../runinator-wdl-syntax" }
runinator-wdl-sema = { path = "../runinator-wdl-sema" }
