//! Shared workspace error vocabulary.
pub use runinator_models::errors::{
    WORKSPACE_BUSY, WORKSPACE_CACHE_FULL, WORKSPACE_COMMIT_UNCERTAIN, WORKSPACE_CONFLICT,
    WORKSPACE_CORRUPT, WORKSPACE_DICTIONARY as DICTIONARY, WORKSPACE_EXISTS, WORKSPACE_INVALID,
    WORKSPACE_IO, WORKSPACE_JSON, WORKSPACE_LIMIT, WORKSPACE_MISSING, WORKSPACE_POISONED,
};
